spring.application.name=efimero

# App 
app.secret.ttl-minutes=60
app.secret.cleanup-interval-ms=60000
app.encryption.key=${APP_ENCRYPTION_KEY}

# H2 DB Config
spring.datasource.url=jdbc:h2:mem:efimerodb;DB_CLOSE_DELAY=-1

# JPA
spring.jpa.hibernate.ddl-auto=create-drop

# H2 Console (debug)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# JDBC URL: jdbc:h2:mem:secretsharedb

# Error Handling
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

# Logging
logging.level.com.example.efimero=DEBUG
logging.level.org.hibernate.SQL=WARN
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.type.descriptor.sql=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
